### ISSUE TITLE
Custom app build are not creating bin folder in Slicer-build

### ISSUE THREAD

**Issue by sjh26** [KitwareMedical/SlicerCustomAppTemplate#10]
This has been happening on two of my custom apps recently.  I have to manually create the bin folder to allow the build to procede.  @jcfr

**Comment by jcfr** [comment]
Is this issue consistent across platform ?
Does it happen if the current version of the template ? (IOW does it happen with the latest version of Slicer ?)

**Comment by sjh26** [comment]
Yes, this is with the current template and latest Slicer.  Have only tested on windows, will let you know when I have more info.

**Comment by jcfr** [comment]
Error discovered when building SlicerSALT:

```
CMake Error at /work/Stable/SSALT-200-build/CTKAPPLAUNCHER/CMake/ctkAppLauncher.cmake:278 (message):
 DESTINATION_DIR [/work/Stable/SSALT-200-build/Slicer-build/bin] doesn't
 seem to exist !
Call Stack (most recent call first):
 /work/Stable/SSALT-200-build/CTKAPPLAUNCHER/CMake/ctkAppLauncher.cmake:520 (_check_variables_exists)
 /work/Stable/SSALT-200-build/CTKAPPLAUNCHER/CMake/ctkAppLauncher.cmake:411 (ctk_applauncher_configure)
 CMake/SlicerCPack.cmake:80 (ctkAppLauncherConfigureForExecutable)
 CMake/LastConfigureStep/CMakeLists.txt:44 (include)
```
