### ISSUE TITLE
 unable to access 'https://github.com/{{cookiecutter.github_organization}}

### ISSUE THREAD

**Issue by yulaomao** [KitwareMedical/SlicerCustomAppTemplate#11]
When I downloaded it, I encountered the following problems 
$ git clone https://github.com/{{cookiecutter.github_organization}}/{{cookiecutter.github_project}}.git {{cookiecutter.github_project}}
Cloning into '{{cookiecutter.github_project}}'...
fatal: unable to access 'https://github.com/{{cookiecutter.github_organization}}/{{cookiecutter.github_project}}.git/': The requested URL returned error: 400
Is there anyone who can give me some advice? Thank you.

**Comment by jcfr** [comment]
Thanks for the report.

The `SlicerCustomAppTemplate` project is not designed to be used as is. Strings like `{{cookiecutter.github_organization}}` are are placeholders used when generating a new project.

I suggest you follow instructions here: https://github.com/KitwareMedical/SlicerCustomAppTemplate#getting-started

If you have other issues, consider opening a new issue.
