### ISSUE TITLE
SurfaceToolbox builds when disabled

### ISSUE THREAD

**Issue by vicory** [KitwareMedical/SlicerCustomAppTemplate#13]
The default config has SurfaceToolbox disabled:

https://github.com/KitwareMedical/SlicerCustomAppTemplate/blob/master/%7B%7Bcookiecutter.project_name%7D%7D/CMakeLists.txt#L126

But Slicer sets a separate variable Slicer_BUILD_SurfaceToolbox that is on by default so the modules are built and show up in the UI anyway. I'm not sure what the desired behavior is but the inconsistency should be fixed.

**Comment by jcfr** [comment]
Thanks for point this out 🙏 

This was an oversight.

Could you submit a PR removing `SurfaceToolbox` from `Slicer_QTSCRIPTEDMODULES_DISABLED` and adding the option `Slicer_BUILD_SurfaceToolbox` similar to `Slicer_BUILD_LandmarkRegistration       ` ?
