### ISSUE TITLE
Request access to the {{cookiecutter.github_organization}}/{{cookiecutter.github_project}} repository

### ISSUE THREAD

**Issue by FethiGhazouani** [KitwareMedical/SlicerCustomAppTemplate#30]
How to get access to the `{{cookiecutter.github_organization}}/{{cookiecutter.github_project}}` repository in order to build the SlicerCustomApplication.

Tying the command 

```
git clone https://github.com/{{cookiecutter.github_organization}}/{{cookiecutter.github_project}}.git {{cookiecutter.github_project}}
```

gives a

```
_fatal: unable to access 'https://github.com/{{cookiecutter.github_organization}}/{{cookiecutter.github_project}}.git/': The requested URL returned error: 400
```

**Comment by jcfr** [comment]
Closing. 

The instructions documented in [{{cookiecutter.project_name}}/BUILD.md](https://github.com/KitwareMedical/SlicerCustomAppTemplate/blob/master/%7B%7Bcookiecutter.project_name%7D%7D/BUILD.md) are only intended be used once an application is generated based on the template.

This explains why it fails if followed verbatim.

Reading these posts may help put things in perspective:
* https://blog.kitware.com/slicercat-creating-custom-applications-based-on-3d-slicer/
* https://blog.kitware.com/slicercat-and-python-creating-custom-slicer-applications-with-qt-stylesheets/

Do not hesitate to reach out if you have question or need help working on custom application.
