### ISSUE TITLE
SlicerVirtualReality cannot be included

### ISSUE THREAD

**Issue by cpinter** [KitwareMedical/SlicerCustomAppTemplate#9]
SlicerVirtualReality builds VTKRenderingOpenVR, which is fine, its build directory is [SuperBuild_DIR]\VTKRenderingOpenVR-build. However, when building it, openvr.h is not found. The problem is that the additional include directories contains [SuperBuild_DIR]\OpenVR\headers, but OpenVR is deployed in [SuperBuild_DIR]\slicersources-build\OpenVR.

Any ideas what needs to be changed so that OpenVR is not in slicersources-build but one level above? Thanks!

**Comment by jcfr** [comment]
> Any ideas what needs to be changed so that OpenVR is not in slicersources-build but one level above?

I think this [line](https://github.com/KitwareMedical/SlicerVirtualReality/blob/b54a704e4208aaa20b55b6ba3c345ded3c58d287/SuperBuild/External_OpenVR.cmake#L32) should be updated to use `CMAKE_BINARY_DIR`

**Comment by cpinter** [comment]
Ah so it might be a problem in SlicerVR. I'll try this change with both regular and custom app builds.
Thanks a lot for the quick answer!

**Comment by cpinter** [comment]
I tried the change and interestingly although the tar.gz file was now downloaded in the top-level older instead of slicersources-build, the uncompressed OpenVR folder was still inside slicersources-build, even though the OpenVR_DIR variable contained the path [SuperBuild_DIR]\OpenVR.

Not quite sure what's going on, I couldn't figure out which call does the uncompressing.

**Comment by cpinter** [comment]
Did some more digging, and by changing the SOURCE_DIR from ${proj} to ${CMAKE_BINARY_DIR}/${proj} did the trick. I'll push this change to SlicerVR. Thanks @jcfr for the pointer!
